language: android

notifications:
  email: false

sudo: false


jdk:
  - oraclejdk8

env:
  global:
    - BUILD_TOOLS_VERSION=23.0.3
    - COMPILE_SDK_VERSION=23 


android:
  components:
    - platform-tools
    - tools
    
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$COMPILE_SDK_VERSION


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


script:
  - ./gradlew check
